version: '3.8'

services:
  conductor-service:
    build:
      context: .
      dockerfile: Dockerfile.service
    container_name: conductor_service
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/appuser/app/src
      - ./scripts/docker:/home/appuser/app/scripts/docker # Mapear o script
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/conductor
    networks:
      - conductor_net
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "python", "scripts/docker/healthcheck.py"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - conductor_net

networks:
  conductor_net:
    driver: bridge

volumes:
  mongodb_data:
