version: '3.8'

services:
  conductor-api:
    build: .
    container_name: conductor-api-1
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "container_name={{.Name}}"
    networks:
      - primoia-network

networks:
  primoia-network:
    name: primoia-monorepo_primoia-network
    external: true