version: '3.8'

services:
  conductor-service:
    build:
      context: .
      dockerfile: Dockerfile.service
    container_name: conductor_service
    ports:
      - "8000:8000" # Expondo uma porta para a futura API
    volumes:
      - ./src:/home/appuser/app/src # Montando o código para hot-reloading
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/conductor
    networks:
      - conductor_net
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - conductor_net

networks:
  conductor_net:
    driver: bridge

volumes:
  mongodb_data:
