services:
  conductor-api:
    build: .
    container_name: conductor-api-1
    ports:
      - "8001:8000"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./logs:/app/logs
      - ./projects:/app/projects
      - /home/cezar/.gcp/keys/conductor-key.json:/gcp_key.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp_key.json
      - GOOGLE_GENAI_USE_VERTEXAI=true
      - GOOGLE_CLOUD_PROJECT=gen-lang-client-0338424173
      - GOOGLE_CLOUD_LOCATION=us-central1
    env_file:
      - .env
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: job=conductor
        loki-pipeline-stages: |
          - json:
              expressions:
                level: level
                agent: agent
          - labels:
              level:
              agent:
    networks:
      - primoia-network

networks:
  primoia-network:
    name: primoia-monorepo_primoia-network
    external: true